Dependency graphs for types and values
finos/morphir-elm pull request #651
Opened 2022-04-07 11:16 UTC by klahnunya

# Terms

> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH FINOS/LINUX FOUNDATION (FORMERLY THE SYMPHONY SOFTWARE FOUNDATION CCLA).
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

2022-04-07 14:35 UTC, AttilaMihaly requested changes

2022-04-07 14:35 UTC, AttilaMihaly commented on cli/src/Morphir/Web/DevelopApp.elm
> +                                    HttpError (Http.BadBody "Could not transform Distribution to Repo")
You should move this bit of code into the `update` function. Generating an HTTP error doesn't seem to be right. The `update` function is the one that should create the repo and update the model to put the application in an errored state if the operation fails. In general any substantial processing should happen within the update function.

2022-04-07 14:35 UTC, AttilaMihaly commented on cli/web/graph.html
> +</vis-graph>
This looks like an example. Can you remove it?

2022-04-08 08:59 UTC, klahnunya commented on cli/web/graph.js
> +            title: "FQName"
Yes , this was a temporal placeholder

2022-04-08 08:59 UTC, klahnunya commented on cli/web/graph.js
> +            width: "1000px",
Yeah i think that is possible

2022-04-12 19:59 UTC, AttilaMihaly commented
Merged in a different PR

2022-04-12 19:59 UTC, closed without merging