Working on the CSV files (I will rename this when I have more info)
finos/morphir-elm pull request #830
Opened 2022-07-29 11:09 UTC by fjabeen02

# Terms

> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH FINOS/LINUX FOUNDATION (FORMERLY THE SYMPHONY SOFTWARE FOUNDATION CCLA).
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

2022-08-25 16:23 UTC, jonathanmaw requested changes
This all looks good (though perhaps I've had too much of a hand in it to have perspective about the general shape of it), and a lot of hard work has *definitely* gone into it.

In summary:
* There are a few very minor formatting errors (strange newlines, incorrect capitalisation, weird typos)
* I've had some thoughts on possible improvements to the csv file that might be worth making a task of to do later.
* There are a bunch of types and functions in CsvUtils that I'd like to know if we can do without them.

I also couldn't make an inline comment about it, but "tests-integration/spark/test/src/spark_test_data/expected_results_TestAntiqueSSWhere1.csv" doesn't appear to be used anywhere and can be deleted.

2022-08-25 16:23 UTC, jonathanmaw commented on tests-integration/spark/test/src/SparkTypeTest.scala
> +      .schema(foo_string_schema)
Likewise for all the other tests of maybes

2022-08-26 07:41 UTC, fjabeen02 commented on package-lock.json
> -      "name": "morphir-elm",
Yeah, when I didnt commit the changes it caused that weird npm error I had a couple days ago

2022-08-26 07:42 UTC, fjabeen02 commented on package.json
> +    "elm-doc-preview": "^1.0.7",
I didnt use them but I had to upgrade them to fix that straneg npm error I got a couple days ago.

2022-08-30 10:00 UTC, jonathanmaw commented
I think you accidentally committed a log file in `tests-integration/out.txt`

2022-08-30 10:25 UTC, jonathanmaw approved these changes

2022-08-30 14:45 UTC, AttilaMihaly requested changes
I need to see a documentation on how this testing framework works. I tried to infer it based on the files being added but it's very difficult to see what things are for.

2022-08-30 14:45 UTC, AttilaMihaly commented on package.json
> +    "elm-doc-preview": "^1.0.7",
I just realized that you actually downgraded `elm-doc-preview`. Is there a reason for that?

2022-08-31 11:03 UTC, fjabeen02 commented on package.json
> +    "elm-doc-preview": "^1.0.7",
I think I must have done that whilst trying to debug a version error I was getting. I have reverted back to 3.0.4 now

2022-09-01 12:42 UTC, fjabeen02 commented
@AttilaMihaly  I have now uploaded the documentation to this PR

2022-09-01 13:16 UTC, AttilaMihaly commented
> @AttilaMihaly I have now uploaded the documentation to this PR

Thanks. While I review, can you resolve the conflicts?

2022-09-05 11:17 UTC, AttilaMihaly requested changes
It looks good apart from the minor issues I highlighted in the doc.

2022-09-05 11:28 UTC, fjabeen02 commented on docs/developers-guide/files/spark-testing-framework.md
> +#### 4) Write the code that will run the test on the input data and produce an output data csv
I have fixed both of these mistakes now :)

2022-09-05 11:33 UTC, AttilaMihaly approved these changes

2022-09-05 11:33 UTC, merged