WIP: NodeID and NodePath
finos/morphir-elm pull request #990
Opened 2023-02-02 11:41 UTC by bekand

# Terms

> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH FINOS/LINUX FOUNDATION (FORMERLY THE SYMPHONY SOFTWARE FOUNDATION CCLA).
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

2023-04-20 14:42 UTC, osborneMs requested changes

2023-04-20 14:42 UTC, osborneMs commented on src/Morphir/IR/NodeId.elm
> +getFromList : List NodePathStep -> List NodePathStep -> (NodePath -> NodePath -> a -> Result Error attr) -> List a -> Result Error attr
Add docs on what the various function do. It helps with understanding

2023-04-20 14:42 UTC, osborneMs commented on src/Morphir/IR/NodeId.elm
> +getAttribute : Package.Definition attr attr -> NodeID -> Result Error attr
Could you please alias the type `attr`. Its difficult understanding what that is.

2023-04-20 14:42 UTC, osborneMs commented on src/Morphir/CustomAttribute/CustomAttribute.elm
Not sure if this file should still exist or be renamed. Can you please confirm ?

2023-04-21 09:08 UTC, AttilaMihaly requested changes

2023-04-21 09:08 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
>  nodeIdToString : NodeID -> String
Every exposed function should have some docs.

2023-04-21 09:08 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
> +        mapToTypeOrValue packageName moduleName localName suffix nodePath =
Always specify the types. Especially if there's this many arguments.

2023-04-24 10:56 UTC, AttilaMihaly requested changes

2023-04-24 10:56 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
> +mapPatternAttributesWithNodePath : (NodePath -> attr -> attr2) -> Value.Pattern attr -> Value.Pattern attr2
It feels like this deserves more explanation.

2023-04-24 10:56 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
> +mapPatternAttributesWithNodePathRec : (NodePath -> attr -> attr2) -> NodePath -> Value.Pattern attr -> Value.Pattern attr2
Docs are missing

2023-04-24 10:56 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
> +mapValueAttributesWithNodePath : (NodePath -> attr -> attr2) -> Value attr attr -> Value attr2 attr2
Needs more explanation.

2023-04-24 10:56 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
> +mapTypeAttributeWithNodePath : (NodePath -> attr -> attr2) -> Type attr -> Type attr2
Needs more explanation.

2023-04-24 10:56 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
> +mapTypeAttributeWithNodePathRec : (NodePath -> attr -> attr2) -> NodePath -> Type attr -> Type attr2
Punctuation is missing. I don't see how this function would return an error.

2023-04-24 10:56 UTC, AttilaMihaly commented on src/Morphir/IR/NodeId.elm
> +Return erro if the NodeID is invalid
Punctuation is missing.

2023-04-24 13:03 UTC, AttilaMihaly requested changes

2023-04-24 13:03 UTC, AttilaMihaly commented on src/Morphir/CustomAttribute/CustomAttribute.elm
Is this still necessary? I thought we moved everything to Decorations.

2023-04-24 13:17 UTC, bekand commented on src/Morphir/CustomAttribute/CustomAttribute.elm
I think you are right, that file was unused. I removed it.

2023-04-24 14:04 UTC, AttilaMihaly requested changes
There's one cosmetic change left.

2023-04-24 14:34 UTC, merged